---
title: "database_process"
author: "22150152 渡邉悠音"
date: "2024-05-21"
output: html_document
---

## dplyr処理演習
```{r}
library(tidyverse)

d <- data.frame(
  name = c("太郎", "花子", "三郎", "良子", "次郎", "桜子", "四郎", "松子", "愛子"),
  school = c("南", "南", "南", "南", "南", "東", "東", "東", "東"),
  teacher = c("竹田", "竹田", "竹田", "竹田",  "佐藤", "佐藤", "佐藤", "鈴木", "鈴木"),
  gender = c("男", "女", "男", "女", "男", "女", "男", "女", "女"),
  math = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
  reading = c(1, 5, 2, 4, 5, 4, 1, 5, 4) )

library(DT)
datatable(d)
```

#回答
```{r}
#1
d|> select(name,math)

#2
d|> select(-gender)

#3
d|> slice(3:6)

#4
d|> arrange(name)

#5
d|> arrange(desc(math))

#6
d|> arrange(desc(math),desc(reading))

#7
d|> select(name,reading)

#8
d|> summarize(math_mean=mean(math))

#9
d|> group_by(teacher)%>%
  summarize(math_mean=mean(math))

#10
d|> filter(gender=="女")%>%
  select(name,math)

#11
d|> filter(gender=="男",school=="南")%>%
  select(name,reading)

#12
d|> group_by(teacher)%>%
  filter(n()>=3)

#13
d|> mutate(total=math+reading)

#14
d|> mutate(math100=math*20)

```

